import { NextRequest, NextResponse } from 'next/server'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

export async function POST(req: NextRequest) {
  const { title, severity, content, date } = await req.json()

  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([595, 842]) // A4

  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const courier = await pdfDoc.embedFont(StandardFonts.Courier)

  const colors = {
    black: rgb(0.05, 0.05, 0.05),
    red: rgb(0.91, 0.27, 0.27),
    amber: rgb(0.96, 0.65, 0.14),
    blue: rgb(0.29, 0.56, 0.85),
    gray: rgb(0.4, 0.45, 0.5),
    lightGray: rgb(0.92, 0.93, 0.95),
    white: rgb(1, 1, 1),
  }

  const severityColor = severity === 'P0' ? colors.red : severity === 'P1' ? colors.amber : colors.blue
  const { width, height } = page.getSize()

  // Header bar
  page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: rgb(0.03, 0.04, 0.06) })

  // Severity badge
  page.drawRectangle({ x: 40, y: height - 60, width: 40, height: 22, color: severityColor})
  page.drawText(severity, { x: 48, y: height - 52, size: 10, font: helveticaBold, color: colors.white })

  // Title
  const titleText = title.length > 55 ? title.slice(0, 55) + '...' : title
  page.drawText(titleText, { x: 90, y: height - 52, size: 13, font: helveticaBold, color: colors.white })

  // Date
  page.drawText(`Generated: ${date}`, { x: 40, y: height - 72, size: 8, font: helvetica, color: rgb(0.5, 0.55, 0.6) })
  page.drawText('PostMortem AI', { x: width - 110, y: height - 72, size: 8, font: helvetica, color: rgb(0.5, 0.55, 0.6) })

  // Content
  let yPos = height - 110
  const lineHeight = 14
  const maxWidth = width - 80
  const sectionHeaders = ['Executive Summary', 'Timeline', 'Root Cause', 'Impact Analysis', 'Action Items', 'Lessons Learned']

  const lines = content.split('\n')

  for (const line of lines) {
    if (yPos < 60) {
      const newPage = pdfDoc.addPage([595, 842])
      yPos = newPage.getSize().height - 60
    }

    const trimmed = line.trim()
    if (!trimmed) { yPos -= lineHeight / 2; continue }

    const isHeader = sectionHeaders.some(h => trimmed.startsWith(`## ${h}`) || trimmed === h)
    const isBullet = trimmed.startsWith('- ') || trimmed.startsWith('• ')
    const isTimestamp = /^\[\d{2}:\d{2}\]/.test(trimmed)

    if (isHeader) {
      if (yPos < height - 140) yPos -= 6
      const headerText = trimmed.replace('## ', '')
      page.drawRectangle({ x: 40, y: yPos - 4, width: maxWidth, height: 18, color: colors.lightGray })
      page.drawText(headerText, { x: 44, y: yPos, size: 10, font: helveticaBold, color: colors.black })
      yPos -= lineHeight + 8
    } else if (isTimestamp) {
      const chunks = wrapText(trimmed, courier, 8, maxWidth - 20)
      for (const chunk of chunks) {
        page.drawText(chunk, { x: 50, y: yPos, size: 8, font: courier, color: rgb(0.2, 0.6, 0.4) })
        yPos -= lineHeight - 2
      }
    } else if (isBullet) {
      const bulletText = trimmed.slice(2)
      const chunks = wrapText(bulletText, helvetica, 9, maxWidth - 25)
      for (let i = 0; i < chunks.length; i++) {
        if (i === 0) page.drawText('•', { x: 48, y: yPos, size: 9, font: helveticaBold, color: colors.gray })
        page.drawText(chunks[i], { x: 60, y: yPos, size: 9, font: helvetica, color: colors.black })
        yPos -= lineHeight - 2
      }
    } else {
      const chunks = wrapText(trimmed, helvetica, 9, maxWidth)
      for (const chunk of chunks) {
        page.drawText(chunk, { x: 40, y: yPos, size: 9, font: helvetica, color: colors.black })
        yPos -= lineHeight - 2
      }
    }
  }

  // Footer
  const lastPage = pdfDoc.getPages()[pdfDoc.getPageCount() - 1]
  lastPage.drawLine({ start: { x: 40, y: 45 }, end: { x: width - 40, y: 45 }, thickness: 0.5, color: colors.lightGray })
  lastPage.drawText('Generated by PostMortem AI — github.com/NidhiSharmaProductLedEngineering', {
    x: 40, y: 30, size: 7, font: helvetica, color: colors.gray
  })

  const pdfBytes = await pdfDoc.save()
  const buffer = Buffer.from(pdfBytes)

  return new NextResponse(buffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="postmortem-${severity}-${Date.now()}.pdf"`,
    },
  })
}

function wrapText(text: string, font: any, size: number, maxWidth: number): string[] {
  const words = text.split(' ')
  const lines: string[] = []
  let current = ''

  for (const word of words) {
    const test = current ? `${current} ${word}` : word
    try {
      const w = font.widthOfTextAtSize(test, size)
      if (w > maxWidth && current) { lines.push(current); current = word }
      else current = test
    } catch { current = test }
  }
  if (current) lines.push(current)
  return lines
}
